version: "3"
services:
  anvil-uplink:
    # if something fails or the server is restarted, the container will restart
    restart: always 
    container_name: anvil-uplink
    image: anvil-uplink
    volumes:
      - ./connect4_cnn_model.h5:/app_folder/connect4_cnn_model.h5
      - ./Hybrid_best_67_val.keras:/app_folder/Hybrid_best_67_val.keras
      - ./final_best_vit_67_val.keras:/app_folder/final_best_vit_67_val.keras
    build: 
      # build the image from the Dockerfile in the current directory
      context: .